spring:
    autoconfigure:
        exclude: org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration
    web:
        resources:
            add-mappings: false

server:
    servlet:
        session:
            cookie:
                same-site: strict

logging:
    level:
        koffeine: debug
        org.springframework.web.servlet.PageNotFound: off
