spring:
    autoconfigure:
        exclude: org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration
    web:
        resources:
            add-mappings: false

logging:
    level:
        koffeine: debug
        org.springframework.web.servlet.PageNotFound: off
