spring:
    autoconfigure:
        exclude: org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration
    web:
        resources:
            add-mappings: false
    jpa:
        open-in-view: false
    datasource:
        url: jdbc:h2:mem:;DB_CLOSE_ON_EXIT=FALSE

logging:
    level:
        koffeine: debug
        org.springframework.web.servlet.PageNotFound: off
